#import "~/api/fragments/static.fragment.gql"

fragment authUserTokens on SignInResponse {
  refresh_token
  access_token
}

fragment authSessionTokens on AuthSession {
  refresh_token
  access_token
}

fragment authUser on SignInResponse {
  id
  email
  firstName
  lastName
  role
  birthday
  canUseAnalyticsData
  countryCode
  createdAt
  updatedAt
}

fragment appConnectedUser on BookUser {
  bookId
  bookRole
  isActive
  book {
    name
    bookNumber
    envType
  }
}

fragment appUser on User {
  birthday
  canUseAnalyticsData
  countryCode
  createdAt
  email
  firstName
  id
  lastName
  phoneNumber
  role
  suspended
  updatedAt
  verified
  connectedBookUsers {
    ...appConnectedUser
  }
}

fragment appBook on Book {
  id
  createdAt
  updatedAt
  bookNumber
  envType
  isActive
  isSeeded
  name
  primaryCurrencyCode
  system
  systemUserId
  activeCurrencies {
    ...selectCurrency
  }
}

fragment sessionRefreshData on AuthSession {
  ...authSessionTokens
  activeUserId
  activeBookId
  activeUser {
    ...appUser
  }
  activeBook {
    ...appBook
  }
}

fragment authSessionStatus on AuthSessionStatus {
  activeUserId
  activeBookId
  activeUser {
    ...appUser
  }
  activeBook {
    ...appBook
  }
}
