fragment baseConnectedUser on BookUser {
  userId
  bookRole
  bookId
}

fragment homeBookEntry on Book {
  bookNumber
  createdAt
  envType
  id
  isActive
  isSeeded
  name
  primaryCurrencyCode
  system
  systemUserId
  updatedAt
  _count {
    periods
    glAccounts
    transactions
    transactionTypes
    accountTypes
    activeCurrencies
  }
  connectedBookUsers {
    ...baseConnectedUser
  }
}

fragment baseBookData on Book {
  bookNumber
  createdAt
  envType
  id
  isActive
  isSeeded
  name
  primaryCurrencyCode
  system
  systemUserId
  updatedAt
  connectedBookUsers {
    ...baseConnectedUser
  }
}
