fragment staticCountry on Country {
  code
  countryCurrencyCode
  id
  locale
  name
  timezones
}

fragment staticCurrency on Currency {
  code
  currencyFraction
  currencyFractionUnits
  currencySymbol
  id
  name
}

fragment selectCountry on Country {
  code
  name
}

fragment selectCurrency on Currency {
  code
  name
  currencySymbol
}
