fragment staticCountry on Country {
  code
  countryCurrencyCode
  id
  locale
  name
  timezones
}

fragment staticCurrency on Currency {
  code
  currencyFraction
  currencyFractionUnits
  currencySymbol
  id
  name
}

fragment selectCountry on Country {
  code
  name
}

fragment selectCurrency on Currency {
  code
  name
  currencySymbol
}

fragment listCurrency on Currency {
  id
  isActive
  updatedAt
  createdAt
  code
  name
  currencyFraction
  currencyFractionUnits
  currencySymbol
  countries {
    ...selectCountry
  }
}

fragment listCountry on Country {
  id
  isActive
  createdAt
  updatedAt
  name
  code
  countryCurrencyCode
  locale
  timezones
  countryPrimaryCurrency {
    ...selectCurrency
  }
}
