#import "~/api/fragments/auth.fragment.gql"

mutation signin($input: LoginInput!) {
  signin(input: $input) {
    access_token
    ...authUser
  }
}

mutation logout {
  logout {
    uid
    userId
    email
  }
}

mutation refreshTokens {
  refreshSession {
    ...sessionRefreshData
  }
}

query activeUser {
  me {
    ...appUser
  }
}

mutation setCurrentBook($bookId: String!) {
  setActiveBook(bookId: $bookId) {
    ...sessionRefreshData
  }
}

mutation clearCurrentBook {
  clearActiveBook {
    ...sessionRefreshData
  }
}

query activeBookUser {
  me {
    ...appUser
  }
}

query currentSessionData {
  currentSession {
    ...authSessionStatus
  }
}
