#import "~/api/fragments/book.fragment.gql"

mutation newProductionBook($input: NewProductionBookInput!) {
  newProductionBook(input: $input) {
    ...baseBookData
  }
}

mutation seedProductionBook($id: String!) {
  seedProductionBook(id: $id) {
    ...homeBookEntry
  }
}

query getBookBase($input: BookFindInput!) {
  book(input: $input) {
    ...baseBookData
  }
}

mutation createBookUser($input: NewBookUserInput!) {
  createBookUser(input: $input) {
    ...connectedUserResult
  }
}

query searchBookEntities($where: BookEntityWhereInput!) {
  searchBookEntities(where: $where) {
    ...baseEntityData
  }
}
