#import "~/gql-docs/fragments/static.fragment.gql"

query staticLists {
  countries(input: { isActive: { equals: true } }) {
    ...staticCountry
  }
  currencies(where: { isActive: { equals: true } }) {
    ...staticCurrency
  }
}

query dropdownStaticLists {
  countries(input: { isActive: { equals: true } }) {
    ...selectCountry
  }
  currencies(where: { isActive: { equals: true } }) {
    ...selectCurrency
  }
}

query searchCountriesPublic($input: CountryWhereInput!) {
  countries(input: $input) {
    ...staticCountry
  }
}
